"""empty message

Revision ID: 1f81d2549a4e
Revises: fa78f3a0bc26
Create Date: 2020-05-03 02:10:40.931482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f81d2549a4e'
down_revision = 'fa78f3a0bc26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('percent_mark', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('clash')
    op.drop_table('postclashlink')
    op.drop_table('postaccountlink')
    op.drop_table('clashaccountlink')
    op.add_column('account', sa.Column('Team', sa.Integer(), nullable=True))
    op.add_column('account', sa.Column('badges', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'account', 'team', ['Team'], ['id'])
    op.add_column('task', sa.Column('text', sa.Text(), nullable=False))
    op.drop_column('task', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('name', sa.TEXT(), nullable=False))
    op.drop_column('task', 'text')
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'badges')
    op.drop_column('account', 'Team')
    op.create_table('clashaccountlink',
    sa.Column('clash_id', sa.INTEGER(), nullable=False),
    sa.Column('account_id', sa.INTEGER(), nullable=False),
    sa.Column('relationType', sa.VARCHAR(length=24), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['clash_id'], ['clash.id'], ),
    sa.PrimaryKeyConstraint('clash_id', 'account_id')
    )
    op.create_table('postaccountlink',
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('account_id', sa.INTEGER(), nullable=False),
    sa.Column('relationType', sa.VARCHAR(length=24), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'account_id')
    )
    op.create_table('postclashlink',
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('clash_id', sa.INTEGER(), nullable=False),
    sa.Column('relationType', sa.VARCHAR(length=24), nullable=True),
    sa.ForeignKeyConstraint(['clash_id'], ['clash.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'clash_id')
    )
    op.create_table('clash',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('submission')
    op.drop_table('team')
    # ### end Alembic commands ###
