"""accountrole

Revision ID: 3077f28babcb
Revises: 24c6cdf150b6
Create Date: 2020-05-03 04:19:06.219199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3077f28babcb'
down_revision = '24c6cdf150b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account") as batch_op:
        batch_op.add_column(sa.Column('role', sa.Text(), nullable=False, server_default="student"))
        batch_op.alter_column('role', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("account") as batch_op:
        batch_op.drop_column('role')
    # ### end Alembic commands ###
