"""newbadges

Revision ID: d5b96390eca2
Revises: 4d998c6ec630
Create Date: 2020-05-04 12:19:25.998097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b96390eca2'
down_revision = '4d998c6ec630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('awarder_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['awarder_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('badge')
    # ### end Alembic commands ###
