"""clashrooms

Revision ID: fa78f3a0bc26
Revises: 
Create Date: 2020-05-02 19:59:40.664268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa78f3a0bc26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Text(), nullable=False),
    sa.Column('pwrd', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clashaccountlink',
    sa.Column('clash_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('relationType', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['clash_id'], ['clash.id'], ),
    sa.PrimaryKeyConstraint('clash_id', 'account_id')
    )
    op.create_table('postaccountlink',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('relationType', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'account_id')
    )
    op.create_table('postclashlink',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('clash_id', sa.Integer(), nullable=False),
    sa.Column('relationType', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['clash_id'], ['clash.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('post_id', 'clash_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postclashlink')
    op.drop_table('postaccountlink')
    op.drop_table('clashaccountlink')
    op.drop_table('task')
    op.drop_table('post')
    op.drop_table('clash')
    op.drop_table('account')
    # ### end Alembic commands ###
